import './globals.css'
import "../components/css/footer.css"
import { Inter } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.css"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ fontSize:'16px' }} >
    <head>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Castoro+Titling&family=Fasthand&family=League+Script&family=Lora:ital,wght@1,500;1,700&display=swap" rel="stylesheet"/>
    </head>
      <body   className={inter.className}>{children}</body>
      {/* <body  style={{backgroundColor:"rgb(12,121,12)"}} className={inter.className}>{children}</body> */}
    </html>
  )
}
